routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PostController@index');
Route::get('/home', 'HomeController@index')->name('home');

Route::resource('posts', 'PostController');

Route::post('comments/{slug}/store', 'CommentController@store')->name('comments.store');
Route::get('comments/{id}/edit', 'CommentController@edit')->name('comments.edit');
Route::put('comments/{id}/update', 'CommentController@update')->name('comments.update');
Route::delete('comments/{id}', 'CommentController@destroy')->name('comments.destroy');

Auth::routes();

resources/views/forum/create.blade.php
@extends('layouts.master')

@section('title', 'Create Post')

@section('content')
    <div class="container">
        <h1 class="mt-5">Create Post</h1>
        <hr>

        <form action="{{ route('posts.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label>Title</label>
                <input type="text" name="title" class="form-control" placeholder="The title of the post">
            </div>
            <div class="form-group">
                <label>Category</label>
                <select name="category_id" class="form-control">
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group">
                <label>Body</label>
                <textarea rows="5" type="text" name="body" class="form-control" placeholder="The body of the post"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Publish</button>
        </form>
    </div>
@endsection

resources/views/forum/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Post')

@section('content')
    <div class="container">
        <h1 class="mt-5">Edit Post</h1>
        <hr>

        <form action="{{ route('posts.update', $post->slug) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="form-group">
                <label>Title</label>
                <input type="text" name="title" class="form-control"
                    placeholder="The title of the post" value="{{ old('title') ?? $post->title }}">
            </div>
            <div class="form-group">
                <label>Category</label>
                <select name="category_id" class="form-control">

                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}"
                            {{ ($category->id === $post->category_id) ? 'selected="true"' : '' }}">
                            {{ $category->name }}
                        </option>
                    @endforeach

                </select>
            </div>
            <div class="form-group">
                <label>Body</label>
                <textarea rows="5" type="text" name="body" class="form-control"
                    placeholder="The body of the post">{{ old('body') ?? $post->body }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/forum/index.blade.php
@extends('layouts.master')

@section('title', 'Forum')

@section('content')
    <div class="container">
        <h1 class="mt-5">Simple Forum</h1>
        <p class="lead mb-1">Hello, John Doe</p>
        <a href="{{ route('posts.create') }}" class="btn btn-sm btn-primary mb-3">
            Create new post
        </a>
        <hr>

        <div class="row post">
            @foreach ($posts as $post)
                <div class="col-md-12 mb-2">
                    <a href="{{ route('posts.show', $post->slug) }}" class="h4">
                        {{ $post->title }}
                    </a>
                    <p class="text-muted mb-2">{{ $post->user->name }}</p>
                    <p class="text-muted mt-2">{{ $post->comments->count() }} comments</p>
                    <hr>
                </div>
            @endforeach
            
            <center style="margin:0 auto">
                {!! $posts->links() !!}
            </center>
        </div>
    </div>
@endsection

resources/views/forum/show.blade.php
@extends('layouts.master')

@section('title', $post->title)

@section('css')
    <style>
        #delete-form, #delete-comment {
            display: inline-block;
        }
    </style>
@endsection

@section('content')
    <div class="container">
        <h2 class="mt-5">{{ $post->title }}</h2>

        @can ('update', $post)
            <a href="{{ route('posts.edit', $post->slug) }}"class="btn btn-sm btn-warning">
                Edit
            </a>
        @endcan

        @can ('delete', $post)
            <form id="delete-form" onsubmit="return confirm('Are you sure?')"
                action="{{ route('posts.destroy', $post->slug) }}" method="POST">
                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            </form>
        @endcan

        <p class="h5 mb-2 mt-4">{{ $post->body }}</p>
        
        <a href="#" class="badge badge-secondary">{{ $post->category->name }}</a>
        <p>{{ $post->created_at }}</p>
        <hr>
        <div class="row post">
            <h5 class="ml-4">{{ $post->comments->count() }} comments</h5>
            <hr>
            @foreach ($post->comments as $comment)
                <div class="col-md-12 mb-2">
                    <p class="mb-1">
                        <strong>{{ $comment->user->name }}</strong> -
                        <small>{{ $comment->updated_at }}</small>
                    </p>
                    <p class="mt-1 mb-1">{{ $comment->comment }}</p>

                    @can ('update', $comment)
                        <a href="{{ route('comments.edit', $comment->id) }}" class="btn btn-sm btn-warning">Edit</a>
                    @endcan

                    @can ('delete', $comment)
                        <form id="delete-comment" onsubmit="return confirm('Are you sure?')"
                            action="{{ route('comments.destroy', $comment->id) }}" method="POST">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    @endcan
                    <hr>
                </div>
            @endforeach

            @auth
                <div class="col-md-12">
                    <form action="{{ route('comments.store', $post->slug) }}" method="POST">
                        @csrf
                        <textarea rows="5" type="text" name="comment"
                            class="form-control mb-2" placeholder="Your comment.."></textarea>
                        <button type="submit" class="btn btn-primary mb-5">Submit</button>
                    </form>
                </div>
            @endauth
        </div>
    </div>
@endsection